FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Libreria.MVC/Libreria.MVC.csproj", "Libreria.MVC/"]
COPY ["API.Consumer/API.Consumer.csproj", "API.Consumer/"]
COPY ["LibreriaModelo/LibreriaModelo.csproj", "LibreriaModelo/"]
COPY ["Libreria.Servicios/Libreria.Servicios.csproj", "Libreria.Servicios/"]

RUN dotnet restore "Libreria.MVC/Libreria.MVC.csproj"

COPY . .

WORKDIR "/src/Libreria.MVC"

RUN dotnet build "Libreria.MVC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Libreria.MVC.csproj" -c Release -o /app/publish /p:UseAppHost=false /p:ErrorOnDuplicatePublishOutputFiles=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Libreria.MVC.dll"]