FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Libreria.API/Libreria.API.csproj", "Libreria.API/"]
COPY ["LibreriaModelo/LibreriaModelo.csproj", "LibreriaModelo/"]

RUN dotnet restore "Libreria.API/Libreria.API.csproj"

COPY . .

WORKDIR "/src/Libreria.API"
RUN dotnet build "Libreria.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Libreria.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Libreria.API.dll"]